// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GitInsight.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.0");

            modelBuilder.Entity("Data.DBAuthor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBRepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DBRepositoryId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("Data.DBCommit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBAuthorId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DBRepositoryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DBAuthorId");

                    b.HasIndex("DBRepositoryId");

                    b.ToTable("Commits");
                });

            modelBuilder.Entity("Data.DBRepository", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LatestCommit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Repositories");
                });

            modelBuilder.Entity("Data.DBAuthor", b =>
                {
                    b.HasOne("Data.DBRepository", null)
                        .WithMany("Authors")
                        .HasForeignKey("DBRepositoryId");
                });

            modelBuilder.Entity("Data.DBCommit", b =>
                {
                    b.HasOne("Data.DBAuthor", null)
                        .WithMany("Commits")
                        .HasForeignKey("DBAuthorId");

                    b.HasOne("Data.DBRepository", null)
                        .WithMany("Commits")
                        .HasForeignKey("DBRepositoryId");
                });

            modelBuilder.Entity("Data.DBAuthor", b =>
                {
                    b.Navigation("Commits");
                });

            modelBuilder.Entity("Data.DBRepository", b =>
                {
                    b.Navigation("Authors");

                    b.Navigation("Commits");
                });
#pragma warning restore 612, 618
        }
    }
}
